import fs from 'node:fs';
import path from 'node:path';

import {
  blockValue,
  parseFrontmatterBlocks,
  renderFrontmatterBlocks,
  splitFrontmatter,
} from './skills.js';

const MAX_NAME = 64;
const VALID_NAME = /^[a-z0-9][a-z0-9-]*$/;

/** The name a skill is published under on a given host. */
export function emittedName(canonicalName, host) {
  return host.namespace === 'name-prefix' ? `${host.prefix}-${canonicalName}` : canonicalName;
}

/**
 * Rewrite references to sibling skills so a prefixed install doesn't point at
 * names that no longer exist on that host. Only whole-token matches are
 * touched, so `engineering-guide` inside `engineering-guidelines` is left alone.
 */
export function rewriteReferences(text, canonicalNames, host) {
  if (host.namespace !== 'name-prefix') return text;
  let out = text;
  for (const name of canonicalNames) {
    out = out.replace(new RegExp(`(?<![\\w-])${name}(?![\\w-])`, 'g'), `${host.prefix}-${name}`);
  }
  return out;
}

/**
 * Build one host's version of a skill.
 * Frontmatter is rebuilt from the host's allowlist rather than filtered, so a
 * host never receives a key it doesn't understand (Claude's `model` must not
 * leak into a Codex install).
 */
export function emitSkill({
  text,
  canonicalName,
  host,
  model = null,
  invocation = 'explicit',
  canonicalNames = [],
}) {
  const { frontmatter, body, hasFrontmatter } = splitFrontmatter(text);
  if (!hasFrontmatter) throw new Error(`Skill "${canonicalName}" has no frontmatter`);

  const name = emittedName(canonicalName, host);
  if (!VALID_NAME.test(name) || name.length > MAX_NAME) {
    throw new Error(`Skill "${canonicalName}" emits an unusable name "${name}" on host ${host.name}`);
  }

  // Siblings, not self: the skill's own name is set explicitly below.
  const siblings = canonicalNames.filter((other) => other !== canonicalName);
  const source = new Map(parseFrontmatterBlocks(frontmatter).map((block) => [block.key, block]));

  const blocks = [];
  for (const key of host.frontmatterKeys) {
    if (key === 'name') {
      blocks.push({ key, lines: [`name: ${name}`] });
    } else if (key === 'model') {
      if (model) blocks.push({ key, lines: [`model: ${model}`] });
    } else if (key === 'disable-model-invocation') {
      // The orchestrator is the workflow's only model-reachable entry point.
      // Every other skill stays human-unreachable-by-accident so that a gate
      // either ran on the routing table or is visibly absent.
      blocks.push({ key, lines: [`disable-model-invocation: ${invocation !== 'auto'}`] });
    } else if (key === 'description') {
      const existing = source.get('description');
      if (existing) {
        blocks.push({
          key,
          lines: [`description: ${rewriteReferences(blockValue(existing), siblings, host)}`],
        });
      }
    } else if (source.has(key)) {
      blocks.push(source.get(key));
    }
  }

  const rendered = `---\n${renderFrontmatterBlocks(blocks)}\n---\n`;
  return { name, dirName: name, text: rendered + rewriteReferences(body, siblings, host) };
}

/** `plugin.json` - its `name` is what becomes the `aether-wfl:` prefix in Claude Code. */
export function pluginManifest(host, { version, description, author, license, homepage }) {
  return {
    name: host.prefix,
    description,
    version,
    author,
    license,
    homepage,
  };
}

/** `marketplace.json`. The entry name must equal the manifest name or install fails. */
export function marketplaceManifest(host, { version, description, author }) {
  return {
    name: host.prefix,
    description: `Local marketplace generated by aether-workflow for ${host.name}`,
    owner: author,
    plugins: [
      {
        name: host.prefix,
        source: `./${path.posix.join(...host.skillsSubdir.split('/').slice(0, -1))}`,
        description,
        version,
      },
    ],
  };
}

/**
 * Compute every file a host install would write, without touching the disk.
 * `install --dry-run` and the tests both read this.
 */
export function planEmission({ host, skills, pkg }) {
  const canonicalNames = skills.map((skill) => skill.name);
  const files = [];
  const names = [];

  for (const skill of skills) {
    const emitted = emitSkill({
      text: fs.readFileSync(skill.source, 'utf8'),
      canonicalName: skill.name,
      host,
      model: skill.model,
      invocation: skill.invocation,
      canonicalNames,
    });
    names.push(emitted.name);
    files.push({
      path: path.join(host.target, host.skillsSubdir, emitted.dirName, 'SKILL.md'),
      contents: emitted.text,
    });
  }

  if (host.namespace === 'plugin') {
    const pluginRoot = path.join(host.target, ...host.skillsSubdir.split('/').slice(0, -1));
    files.push({
      path: path.join(pluginRoot, '.claude-plugin', 'plugin.json'),
      contents: `${JSON.stringify(pluginManifest(host, pkg), null, 2)}\n`,
    });
    files.push({
      path: path.join(host.target, '.claude-plugin', 'marketplace.json'),
      contents: `${JSON.stringify(marketplaceManifest(host, pkg), null, 2)}\n`,
    });
  }

  return { host, files, names };
}

/**
 * Directories under a host's skills root that this workflow owns.
 * A name-prefix host shares its directory with unrelated skills, so ownership
 * is claimed by the prefix and never by the root itself - clearing the root
 * would delete the user's other skills.
 */
export function ownedSkillDirs(host) {
  const skillsRoot = path.join(host.target, host.skillsSubdir);
  if (!fs.existsSync(skillsRoot)) return [];
  const owned = (name) => (host.namespace === 'name-prefix' ? name.startsWith(`${host.prefix}-`) : true);
  return fs
    .readdirSync(skillsRoot, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && owned(entry.name))
    .map((entry) => path.join(skillsRoot, entry.name));
}

/** Write a planned emission, clearing only owned directories so renames don't linger. */
export function writeEmission(emission) {
  for (const dir of ownedSkillDirs(emission.host)) {
    fs.rmSync(dir, { recursive: true, force: true });
  }
  for (const file of emission.files) {
    fs.mkdirSync(path.dirname(file.path), { recursive: true });
    fs.writeFileSync(file.path, file.contents);
  }
  return emission.files.length;
}
